### ISSUE TITLE
Server runs fine but messages don't show up without refresh.

### ISSUE THREAD

**Issue by elorest** [nithinbekal/actioncable-chat-example#13]
Reddis is running on the right port. 6379
./bin/servers are running # I tried it both with cable and rails servers and just ./bin/rails s as since the readme said it was configured to run both.
The log shows the cables being sent without errors. I can connect to reddis fine. It just seems like nothing happens on the page. I tried both safari and chrome. I checked the js console and didn't see any errors.
I followed the instructions exactly and I'm running ruby 2.2.2. Any ideas?﻿

**Comment by nithinbekal** [comment]
That's strange. Could you try running the ["basic" branch](https://github.com/nithinbekal/actioncable-chat-example/tree/basic), which contains a much simpler version of the app? That one needs a separate cable server to run, so it might make it easier to find out where the problem's coming from.

**Comment by elorest** [comment]
I tried that as well. I did just get it running fine on my imac though. So even though I have the most recent version of chrome I deleted it and reinstalled. It now works fine. Really bizzare but solved sort of. Safari is still having issues. If I look at the networking tab it looks like it's not creating a socket.
