### ISSUE TITLE
Could not find gem 'actioncable

### ISSUE THREAD

**Issue by athiraramanan** [nithinbekal/actioncable-chat-example#14]
I am Using Rails new Version and also gem 'actioncable', github: 'rails/actioncable' and when i try to bundle install 
Could not find gem 'actioncable (>= 0) ruby' in
git://github.com/rails/actioncable.git (at master).
Source does not contain any versions of 'actioncable (>= 0) ruby'

**Comment by nithinbekal** [comment]
Hey! ActionCable recently got merged into Rails, so you no longer need actioncable gem in the gemfile. Can you try removing that and running bundle install again?

**Comment by kbrock** [comment]
Also, a few patches have gone into rails. Like the relative path and a rack middleware alternative. Will try and circle back
